### ISSUE TITLE
Add support for color multiplying for grass and foliage

### ISSUE THREAD

**Issue by pixelpapercraft** [pixelpapercraft/pixel-papercraft-generator-builder#12]
From @NinjolasNJM

**Comment by pixelpapercraft** [comment]
https://en.wikipedia.org/wiki/Blend_modes#Overlay

**Comment by NinjolasNJM** [comment]
I think that the blend mode for grass, foliage etc is much closer to multiply than it is to overlay. In game, the coloring of a grass block looks like this:
![2021-07-20_10 18 21](https://user-images.githubusercontent.com/16890123/126350654-6b794ee7-4e9e-4e22-9083-41132da1a852.png)

By adding a layer with the biome color from the Minecraft Wiki (https://minecraft.fandom.com/wiki/Tint#Grass_2) on top of the grayscale grass block top texture in GIMP and use the Multiply blend mode for it, we get this:
![Screen Shot 2021-07-20 at 10 18 37 AM](https://user-images.githubusercontent.com/16890123/126351026-9556a973-fd16-4655-a2e4-adc5f86a6d1c.png)

However, using the Overlay blend mode, you get this:
![Screen Shot 2021-07-20 at 10 20 15 AM](https://user-images.githubusercontent.com/16890123/126351166-04684492-9104-48f9-8812-360b7da73c22.png)

**Comment by RubenVerg** [comment]
Can confirm Minecraft code uses multiply

**Comment by pixelpapercraft** [comment]
@NinjolasNJM @RubenVerg thanks 👍

**Comment by NinjolasNJM** [comment]
You're welcome!

**Comment by pixelpapercraft** [comment]
First release of blending is ready for testing.

https://github.com/pixelpapercraft/pixel-papercraft-generator-builder#blending-colors

**Comment by pixelpapercraft** [comment]
Done
