### ISSUE TITLE
Final Block Generator Changes Didn't Carry Over From Original Closed Repo

### ISSUE THREAD

**Issue by NinjolasNJM** [pixelpapercraft/pixel-papercraft-generator-builder#4]
My PR from the original repo that added doors, trapdoors and snow layers to the Block Generator as well as added full rotation and reflection support to it was approved there, but the changes didn't make their ways here.

**Comment by pixelpapercraft** [comment]
Thanks for letting me know @NinjolasNJM, I've brought those changes across now. I've also published them live. Can you please take a look and confirm?

**Comment by NinjolasNJM** [comment]
Yeah, they do work
